### ISSUE TITLE
Seeking New Ownership

### ISSUE THREAD

**Issue by xaque208** [opus-codium/puppet-ssh#63]
For many years, Puppet has been the core of my infrastructure needs.  That has changed in the last 9 months, and I've begun a new path that I hope will carry me as long as Puppet has.

For those that may still benefit from any of this code, you all deserve maintainers that will give it the attention required, and that is no longer me. And if I'm being honest, it hasn't been me for longer than I'm ready to admit.

So, for those few, I request that if anyone wants this to persist, fork it and make a new.  I plan to archive all of the Puppet repos under my name in the coming month and collapse all of my puppet related infrastructure. Expect no more releases from me.  Any coordination/communication of forks should happen quickly.

Thank you for all the collaboration over the years.  It has been a real privilege.

**Comment by smortex** [comment]
Hey! After speaking with @neomilium, we would like to take care of this project and maintain it as a part of the modules we already maintain under the @opus-codium organization.  If you are okay with this, you can transfer the repository to my account so that I can continue to make this module live without loosing the PR and issues history :wink: 

Thank you for your great work on this module over the years!

**Comment by neomilium** [comment]
@xaque208 Thank you for your contribution around Puppet!

**Comment by xaque208** [comment]
Thanks folks, much appreciated. I can transfer the repo once the fork is deleted under `smortex/`.

**Comment by smortex** [comment]
:wave: Ooops! Everything is this repo was old and merged, I removed my fork.  Thanks @xaque208 !
